# https://github.com/Rooby-Roo/KeymastersKeepGameArchive
from __future__ import annotations

from typing import List

from dataclasses import dataclass

from Options import Toggle

from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

from ..enums import KeymastersKeepGamePlatforms


@dataclass
class AnyGameTasksArchipelagoOptions:
    any_game_tasks_include_exploit_tasks: AnyGameTasksIncludeExploitTasks


class AnyGameTasksGame(Game):
    # Initial implementation by RoobyRoo

    name = "Any Game Tasks"
    platform = KeymastersKeepGamePlatforms.META
    is_adult_only_or_unrated = False

    options_cls = AnyGameTasksArchipelagoOptions

    def optional_game_constraint_templates(self) -> List[GameObjectiveTemplate]:
        return [
            GameObjectiveTemplate(
                label="Perform all tasks in different games (if possible)",
                data={},
            ),
            GameObjectiveTemplate(
                label="Perform all tasks in the same game (if possible)",
                data={},
            ),
            GameObjectiveTemplate(
                label="Perform all tasks in games from the same genre (if possible)",
                data={},
            ),
            GameObjectiveTemplate(
                label="Perform all tasks from a fresh save file (if possible)",
                data={},
            ),

        ]

    def game_objective_templates(self) -> List[GameObjectiveTemplate]:
        return [
            GameObjectiveTemplate(
                label="TASK",
                data={
                    "TASK": (self.base_actions, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=284,
            ),
            GameObjectiveTemplate(
                label="TASK",
                data={
                    "TASK": (self.exploit_actions, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=12,
            ),
        ]

    @staticmethod
    def base_actions() -> List[str]:
        return [
            "Activate a landmine",
            "Alter the flow of traffic",
            "Alter the flow of water",
            "Alter the time of day",
            "Alter the weather",
            "Attempt the daily challenge",
            "Automate something indefinitely",
            "Become bigger",
            "Become blessed",
            "Become blinded",
            "Become cursed",
            "Become frozen",
            "Become infected",
            "Become intoxicated",
            "Become invisible",
            "Become on fire",
            "Become over-encumbered",
            "Become poisoned",
            "Become smaller",
            "Become stunned",
            "Break a bone",
            "Break a piece of equipment",
            "Break glass",
            "Build a barricade",
            "Build a bridge",
            "Build a campfire",
            "Build a house",
            "Build a statue",
            "Build a turret",
            "Burn something down",
            "Buy out a shop's entire inventory",
            "Cast a magic spell",
            "Catch a bug",
            "Catch a fish",
            "Catch a non-fish item while fishing",
            "Catch something in a net",
            "Catch something thrown",
            "Click a button",
            "Climb a ladder",
            "Climb a mountain",
            "Climb a wall",
            "Commit a crime",
            "Complete a collection",
            "Complete a quick time event",
            "Complete a side quest",
            "Complete a skill check",
            "Complete a timed challenge",
            "Complete a tutorial",
            "Completely fill your inventory",
            "Cook a meal",
            "Craft something",
            "Crash land",
            "Crawl through a tunnel",
            "Create a creature",
            "Cross the entire map",
            "Dance",
            "Deal critical damage",
            "Decode something",
            "Defeat a boss",
            "Detonate a bomb",
            "Dig a hole",
            "Dig around in some trash",
            "Do a backflip",
            "Do a lap in a race",
            "Double jump",
            "Draw a card",
            "Draw a picture",
            "Drink a potion",
            "Drink water",
            "Drive a car",
            "Eat until you are full",
            "Enter a portal",
            "Escape a prison cell",
            "Explode yourself",
            "Fall into a bottomless pit",
            "Fall into a trap",
            "Fall to your death",
            "Fast travel",
            "Find a bonus level",
            "Find a dinosaur",
            "Find a frog",
            "Find a god",
            "Find an egg",
            "Find a police officer",
            "Find a secret passage",
            "Find a ghost",
            "Find a UFO",
            "Find a unicorn",
            "Find something behind a waterfall",
            "Find something in a cave",
            "Find something in a crate",
            "Find something in a tree",
            "Find something where it doesn't belong",
            "Flirt",
            "Flush a toilet",
            "Fly a spacecraft",
            "Free something from a cage",
            "Fully clear a dungeon",
            "Fully clear a room of enemies",
            "Fully fill a meter",
            "Fully explore a map",
            "Get a headshot",
            "Get an upgrade",
            "Get a one-of-a-kind item",
            "Get a perfect score",
            "Get married",
            "Get something labeled as 'legendary' or 'mythic'",
            "Get something labeled as 'rare'",
            "Get to exactly 1 health",
            "Give marching orders",
            "Glide through the air",
            "Go on a date",
            "Go outside",
            "Go to heaven",
            "Go to hell",
            "Go to jail",
            "Go to the moon",
            "Grow and harvest a plant",
            "Have a machine build/craft something for you",
            "Have a pet/companion kill something on your behalf",
            "Hide in a bush",
            "Hide in a closet",
            "Hide under a bed",
            "Interrupt a ceremony",
            "Jump off a cliff",
            "Jump over something spiky",
            "Kick something",
            "Kill a bird",
            "Kill a bug",
            "Kill a demon or devil",
            "Kill a dragon",
            "Kill a friendly NPC",
            "Kill a giant",
            "Kill a human being",
            "Kill an alien",
            "Kill a robot",
            "Kill a sea creature",
            "Kill a zombie",
            "Kill something with an environmental hazard",
            "Kill something with an explosion",
            "Kill something with electricity",
            "Kill something with fire",
            "Kill something with poison",
            "Kill something with your bare hands",
            "Level up",
            "Light a furnace",
            "Light a torch",
            "Light fireworks",
            "Lose",
            "Lose it all while gambling",
            "Make a million dollars",
            "Make an NPC angry",
            "Make an NPC cry",
            "Make an NPC dance",
            "Make an NPC laugh",
            "Make an NPC pass out",
            "Make an NPC smile",
            "Make an NPC surrender",
            "Make an NPC teach you a new skill",
            "Make an NPC yell or scream",
            "Make a trade",
            "Meditate or pray",
            "Obtain 100 coins",
            "Obtain a crystal",
            "Obtain a diamond ring",
            "Obtain a feather",
            "Obtain a full set of armor",
            "Obtain a key",
            "Obtain a map",
            "Obtain medicine",
            "Obtain an achievement",
            "Obtain an extra life",
            "Obtain a pet",
            "Obtain a sword",
            "Obtain a trophy",
            "Obtain candy",
            "Obtain honey",
            "Open a door",
            "Open a jar or bottle",
            "Open a treasure chest",
            "Paint or dye something",
            "Parry an attack",
            "Perform a stealth kill or assassination",
            "Pet a dog",
            "Pick up a creature with your hands/arms",
            "Pilot an aircraft",
            "Plant a tree",
            "Play a game within a game",
            "Play a sport",
            "Pull a lever",
            "Punch an enemy",
            "Put on a helmet",
            "Read a book",
            "Read a note",
            "Read a sign",
            "Ride a bike",
            "Ride an animal",
            "Roll a die",
            "Sabotage a machine",
            "Scare a creature away",
            "Score a goal",
            "See or hear a thunderstorm",
            "See your reflection in a mirror",
            "Serve a customer",
            "Set every slider to the maximum value",
            "Shoot yourself with a gun",
            "Sit down",
            "Sit on a bench",
            "Sleep through the night",
            "Slide across ice",
            "Solve a math problem",
            "Solve a puzzle",
            "Solve a riddle",
            "Speak to a child",
            "Speak to a king or queen",
            "Speak to an old lady",
            "Speak to a shopkeeper about something other than shopping",
            "Spend all of your money",
            "Spill blood",
            "Spin a wheel",
            "Splash water",
            "Stand on a conveyor belt",
            "Stand on a moving platform",
            "Stand on a rooftop",
            "Start a combo",
            "Starve to death",
            "Steer a boat",
            "Step into an ocean",
            "Suffocate",
            "Take a bath or shower",
            "Take off your pants",
            "Take off your shirt",
            "Time travel",
            "Touch grass",
            "Touch lava",
            "Transform an object",
            "Transform yourself",
            "Travel one kilometer",
            "Unlock a cosmetic item",
            "Use a boomerang",
            "Use a bow and arrow",
            "Use a camera",
            "Use a compass",
            "Use a computer",
            "Use a disguise",
            "Use an elevator",
            "Use an emote",
            "Use a flashlight",
            "Use a grappling hook",
            "Use a healing item",
            "Use a hot spring or sauna",
            "Use an in-game save point",
            "Use a jetpack",
            "Use a laser",
            "Use a magic wand",
            "Use a map",
            "Use a musical instrument",
            "Use a parachute",
            "Use a phone",
            "Use a pickaxe",
            "Use a scanner",
            "Use a shield",
            "Use a shovel",
            "Use a slingshot",
            "Use a smoke bomb",
            "Use a special ability",
            "Use a stairwell",
            "Use a stamp or sticker"
            "Use a telescope",
            "Use a vending machine",
            "Use a yo-yo",
            "Use farming equipment",
            "Visit a different dimension",
            "Visit space",
            "Visit your mother",
            "Wake up",
            "Watch a cutscene",
            "Watch something die of old age",
            "Watch the credits",
            "Win",
            "Win a 1v1 battle against another player",
            "Win a game of chance",
            "Witness a crossover event",
            "Zap yourself with electricity",
        ]

    @staticmethod
    def exploit_actions() -> List[str]:
        return [
            "Go out of bounds",
            "Softlock yourself",
            "Crash the game",
            "Use a cheat code",
            "Hit an invisible ceiling",
            "Hit an invisible wall",
            "Reach the world border",
            "Find an easter egg",
            "Find something you weren't supposed to find",
            "Skip a cutscene",
            "See a secret developer message",
            "Open a debug menu",
            "Get the game to tell you to not do that"
        ]


# Archipelago Options
class AnyGameTasksIncludeExploitTasks(Toggle):
    """
    Indicates whether to include tasks that are likely to require using game glitches, hacks, or cheats.
    """

    display_name = "Any Game Tasks: Include Exploit Tasks"
